const API_KEY=CONFIG.API_KEY,SHEET_ID=CONFIG.GOOGLE_SHEET_ID,SHEETS=CONFIG.SHEETS,SHEETS_BASE=`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values`;
let recintos=[],resultadosData={},fotosData={},candidatosData={},map=null,markersLayer=null,searchTimeout=null;

async function leerHoja(n){const u=`${SHEETS_BASE}/${encodeURIComponent(n)}?key=${API_KEY}`;const r=await fetch(u);if(!r.ok)throw new Error(`Error ${r.status}`);const d=await r.json();if(!d.values||d.values.length<2)return[];const h=d.values[0].map(x=>x.toLowerCase().trim());return d.values.slice(1).map(row=>{const o={};h.forEach((k,i)=>{o[k]=(row[i]||'').trim()});return o})}

async function cargarTodosDatos(){showLoader('Cargando resultados...');try{const[res,fot,can]=await Promise.all([leerHoja(SHEETS.RESULTADOS).catch(()=>[]),leerHoja(SHEETS.FOTOS).catch(()=>[]),leerHoja(SHEETS.CANDIDATOS).catch(()=>[])]);resultadosData={};res.forEach(r=>{const c=r.codigo,p=r.partido,v=parseInt(r.votos)||0;if(!c||!p)return;if(!resultadosData[c])resultadosData[c]={};resultadosData[c][p]=(resultadosData[c][p]||0)+v});fotosData={};fot.forEach(f=>{const c=f.codigo,u=f.url_foto,m=f.mesa||'Mesa 1';if(!c||!u)return;if(!fotosData[c])fotosData[c]={};if(!fotosData[c][m])fotosData[c][m]=[];fotosData[c][m].push(u)});candidatosData={};can.forEach(c=>{const d=c.departamento||'',pr=c.provincia||'',mu=c.municipio||'',pa=c.partido||'';if(!d||!mu||!pa)return;const k=`${d}|${pr}|${mu}`;if(!candidatosData[k])candidatosData[k]=[];candidatosData[k].push({partido:pa,nombre:c.candidato||pa,color:c.color||'#6B7280',orden:parseInt(c.orden)||99})});Object.values(candidatosData).forEach(a=>a.sort((a,b)=>a.orden-b.orden));hideLoader();showToast(`${Object.keys(resultadosData).length} recintos con resultados`,'success');renderMapa();actualizarEstadisticas();calcularEstadisticasGlobales()}catch(e){hideLoader();showToast('Error: '+e.message,'error');console.error(e)}}

function inicializarMapa(){const el=document.getElementById('map');if(!el)return;map=L.map('map',{zoomControl:true,attributionControl:false}).setView([-16.5,-64.5],6);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:''}).addTo(map);markersLayer=L.layerGroup().addTo(map);let zt=null;map.on('zoomend',()=>{if(zt)clearTimeout(zt);zt=setTimeout(renderMapa,150)})}

function renderMapa(){if(!map||!markersLayer)return;markersLayer.clearLayers();const depF=document.getElementById('selDep').value,muniF=document.getElementById('selMuni').value,estF=document.getElementById('selEstado').value,busq=document.getElementById('searchInput').value.toLowerCase();const filtered=recintos.filter(r=>{if(depF!=='Todos'&&r.d!==depF)return false;if(muniF!=='Todos'&&r.m!==muniF)return false;if(estF==='ConDatos'&&!resultadosData[r.c])return false;if(estF==='Pendiente'&&resultadosData[r.c])return false;if(busq&&!r.c.toLowerCase().includes(busq)&&!r.r.toLowerCase().includes(busq)&&!r.m.toLowerCase().includes(busq))return false;return true});const zoom=map.getZoom();let radius=zoom<=6?1.5:zoom<=7?2:zoom<=8?2.5:zoom<=10?3.5:zoom<=12?5:zoom<=14?6:8;const lp={};filtered.forEach(r=>{const datos=resultadosData[r.c];let color='#8E99A4',op=0.45;if(datos){const g=obtenerGanador(r,datos);if(g){color=g.color;op=0.85;lp[g.partido]=g.color}else{color='#94A3B8';op=0.6}}const m=L.circleMarker([r.la,r.lo],{radius,fillColor:color,color:datos?'none':'#5C6370',weight:datos?0:1,opacity:op,fillOpacity:op,bubblingMouseEvents:false});m.on('click',e=>{L.DomEvent.stopPropagation(e);L.DomEvent.preventDefault(e);abrirModal(r)});m.addTo(markersLayer)});renderLeyenda(lp);if(muniF!=='Todos')calcularResumenMunicipal(muniF,depF);else document.getElementById('resumenMunicipal').style.display='none'}

function obtenerGanador(rec,datos){const k=`${rec.d}|${rec.p}|${rec.m}`,ca=candidatosData[k];let mx=0,g=null;Object.entries(datos).forEach(([p,v])=>{if(v>mx){mx=v;g=p}});if(!g)return null;if(!ca)return{partido:g,color:'#6B7280',nombre:g};const c=ca.find(x=>x.partido===g);return c?{partido:g,color:c.color,nombre:c.nombre}:{partido:g,color:'#6B7280',nombre:g}}

function renderLeyenda(p){const el=document.getElementById('mapLegend');const k=Object.keys(p);if(!k.length){el.classList.remove('show');return}let h='<div class="legend-title">Ganador por recinto</div>';k.sort().forEach(x=>{h+=`<div class="legend-item"><span class="legend-dot" style="background:${p[x]}"></span>${x}</div>`});h+=`<div class="legend-item"><span class="legend-dot" style="background:#8E99A4;border:1px solid #5C6370"></span>Sin datos</div>`;el.innerHTML=h;el.classList.add('show')}

function calcularEstadisticasGlobales(){const gpr={};let tot=0;recintos.forEach(r=>{const d=resultadosData[r.c];if(!d)return;tot++;const g=obtenerGanador(r,d);if(g)gpr[g.partido]=(gpr[g.partido]||0)+1});const el=document.getElementById('globalStats');if(!el||!tot){if(el)el.style.display='none';return}const items=Object.entries(gpr).sort((a,b)=>b[1]-a[1]);let h='<div class="gstat-title">🏆 Recintos ganados</div>';items.forEach(([pa,cnt])=>{const pct=((cnt/tot)*100).toFixed(1);let col='#6B7280';for(const ca of Object.values(candidatosData)){const c=ca.find(x=>x.partido===pa);if(c){col=c.color;break}}h+=`<div class="gstat-row"><span class="gstat-dot" style="background:${col}"></span><span class="gstat-name">${pa}</span><span class="gstat-count">${cnt}</span><span class="gstat-pct" style="color:${col}">${pct}%</span></div>`});h+=`<div class="gstat-meta">${tot} recintos computados</div>`;el.innerHTML=h;el.style.display=''}

function calcularResumenMunicipal(muni,dep){const recs=recintos.filter(r=>r.m===muni&&(dep==='Todos'||r.d===dep));if(!recs.length){document.getElementById('resumenMunicipal').style.display='none';return}const tot={};let tv=0,cd=0;recs.forEach(r=>{const d=resultadosData[r.c];if(!d)return;cd++;Object.entries(d).forEach(([p,v])=>{tot[p]=(tot[p]||0)+v;tv+=v})});if(!tv){document.getElementById('resumenMunicipal').style.display='none';return}const s=recs[0],k=`${s.d}|${s.p}|${s.m}`,ca=candidatosData[k]||[];const items=Object.entries(tot).map(([p,v])=>{const c=ca.find(x=>x.partido===p);return{partido:p,votos:v,pct:(v/tv*100),color:c?.color||'#6B7280'}}).sort((a,b)=>b.votos-a.votos);document.getElementById('resumenTitulo').textContent=muni;let bar='',lista='';items.forEach(i=>{bar+=`<div class="resumen-barra-seg" style="width:${i.pct}%;background:${i.color}"></div>`});items.forEach((i,idx)=>{lista+=`<div class="resumen-row"><span class="resumen-dot" style="background:${i.color}"></span><span class="resumen-partido">${i.partido}</span><span class="resumen-votos">${i.votos.toLocaleString()}</span><span class="resumen-pct" style="color:${idx===0?i.color:'inherit'}">${i.pct.toFixed(1)}%</span></div>`});document.getElementById('resumenBarra').innerHTML=bar;document.getElementById('resumenLista').innerHTML=lista;document.getElementById('resumenMeta').textContent=`${cd}/${recs.length} recintos · ${tv.toLocaleString()} votos`;document.getElementById('resumenMunicipal').style.display=''}

function getDriveThumbnail(url){let id='';if(url.includes('id='))id=url.split('id=')[1]?.split('&')[0];else if(url.includes('/d/'))id=url.split('/d/')[1]?.split('/')[0];if(id)return`https://lh3.googleusercontent.com/d/${id}=s600`;return url}
function getDriveOpenUrl(url){let id='';if(url.includes('id='))id=url.split('id=')[1]?.split('&')[0];else if(url.includes('/d/'))id=url.split('/d/')[1]?.split('/')[0];if(id)return`https://drive.google.com/file/d/${id}/view`;return url}

function abrirModal(rec){const datos=resultadosData[rec.c],fotos=fotosData[rec.c],k=`${rec.d}|${rec.p}|${rec.m}`,ca=candidatosData[k]||[];document.getElementById('modalTitle').textContent=rec.r;document.getElementById('modalSub').textContent=`${rec.c} · ${rec.m}, ${rec.d} · ${rec.ms||1} mesa(s)`;let html='';if(!datos||!Object.keys(datos).length){html=`<div class="no-data"><div class="no-data-icon">📭</div><div class="no-data-text">Sin resultados</div><div class="no-data-sub">Recinto sin datos cargados</div></div>`}else{let tv=0;Object.values(datos).forEach(v=>tv+=v);const items=Object.entries(datos).map(([p,v])=>{const c=ca.find(x=>x.partido===p);return{partido:p,votos:v,nombre:c?.nombre||p,color:c?.color||'#6B7280',pct:tv>0?(v/tv*100):0}}).sort((a,b)=>b.votos-a.votos);const g=items[0],mx=Math.max(...items.map(i=>i.votos));html+=`<div class="m-stats"><div class="m-stat"><span class="m-stat-v">${tv.toLocaleString()}</span><span class="m-stat-l">votos</span></div><div class="m-stat"><span class="m-stat-v">${rec.ms||1}</span><span class="m-stat-l">mesas</span></div><div class="m-stat"><span class="m-stat-v">${rec.h||0}</span><span class="m-stat-l">hab.</span></div><div class="m-stat winner" style="border-color:${g.color}"><span class="m-stat-v" style="color:${g.color}">🏆 ${g.partido}</span><span class="m-stat-l">${g.pct.toFixed(1)}%</span></div></div>`;html+=`<div class="m-chart">`;items.forEach(i=>{const w=mx>0?Math.max((i.votos/mx*100),3):3;html+=`<div class="m-row"><span class="m-sigla">${i.partido}</span><div class="m-bar-bg"><div class="m-bar-fill" style="width:${w}%;background:${i.color}"></div></div><span class="m-vnum">${i.votos}</span><span class="m-vpct" style="color:${i===g?i.color:''}">${i.pct.toFixed(1)}%</span></div>`});html+=`</div>`}if(fotos&&Object.keys(fotos).length>0){html+=`<div class="m-fotos-head">📸 Actas electorales</div><div class="m-fotos">`;Object.entries(fotos).forEach(([mesa,urls])=>{urls.forEach((url,i)=>{const th=getDriveThumbnail(url),op=getDriveOpenUrl(url);html+=`<div class="m-foto" onclick="window.open('${op}','_blank')"><img src="${th}" alt="${mesa}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="m-foto-fallback" style="display:none">📷</div><span class="m-foto-label">${mesa}</span></div>`})});html+=`</div>`}document.getElementById('modalBody').innerHTML=html;document.getElementById('modalOverlay').classList.add('open');setTimeout(()=>{document.querySelectorAll('.m-bar-fill').forEach(b=>{const w=b.style.width;b.style.width='0';requestAnimationFrame(()=>{b.style.width=w})})},50)}
function cerrarModal(){document.getElementById('modalOverlay').classList.remove('open')}

function buscar(t,cid){const c=document.getElementById(cid);if(!c)return;if(searchTimeout)clearTimeout(searchTimeout);const q=t.trim().toLowerCase();if(q.length<1){c.innerHTML='';c.classList.remove('show');return}searchTimeout=setTimeout(()=>{const res=recintos.filter(r=>r.c.toLowerCase().includes(q)||r.r.toLowerCase().includes(q)||r.m.toLowerCase().includes(q)||r.d.toLowerCase().includes(q)).slice(0,12);if(!res.length){c.innerHTML='<div class="sr-empty">Sin resultados</div>';c.classList.add('show');return}let h='';res.forEach(r=>{const ic=resultadosData[r.c]?'✅':'⏳';h+=`<div class="sr-item" onclick="irA('${r.c}','${cid}')"><span class="sr-icon">${ic}</span><div class="sr-info"><div class="sr-name">${hl(r.r,q)}</div><div class="sr-detail">${hl(r.c,q)} · ${r.m}</div></div></div>`});c.innerHTML=h;c.classList.add('show')},100)}
function hl(t,q){return t.replace(new RegExp(`(${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi'),'<mark>$1</mark>')}
function irA(cod,cid){const r=recintos.find(x=>x.c===cod);if(!r)return;document.getElementById(cid).classList.remove('show');document.getElementById('floatSearch')?.classList.remove('show');if(window.innerWidth<=768)document.getElementById('panel').classList.remove('show');map.setView([r.la,r.lo],14,{animate:true});setTimeout(()=>abrirModal(r),350)}
function llenarFiltros(){const deps=[...new Set(recintos.map(r=>r.d).filter(Boolean))].sort();const s=document.getElementById('selDep');s.innerHTML='<option value="Todos">Todos</option>';deps.forEach(d=>{s.innerHTML+=`<option value="${d}">${d}</option>`})}
function actualizarMunicipios(){const dep=document.getElementById('selDep').value,s=document.getElementById('selMuni');s.innerHTML='<option value="Todos">Todos</option>';if(dep==='Todos')return;[...new Set(recintos.filter(r=>r.d===dep).map(r=>r.m))].sort().forEach(m=>{s.innerHTML+=`<option value="${m}">${m}</option>`})}
function actualizarEstadisticas(){const n=Object.keys(resultadosData).length,t=recintos.length;document.querySelector('#statCargados .stat-num').textContent=n;document.querySelector('#statPendientes .stat-num').textContent=(t-n).toLocaleString();document.querySelector('#statProgreso .stat-num').textContent=(t>0?((n/t)*100).toFixed(1):0)+'%'}
function showLoader(t){document.getElementById('loaderText').textContent=t;document.getElementById('loader').classList.add('show')}
function hideLoader(){document.getElementById('loader').classList.remove('show')}
function showToast(m,type){const t=document.getElementById('toast');document.getElementById('toastIcon').textContent=type==='success'?'✅':type==='error'?'❌':'ℹ️';document.getElementById('toastMsg').textContent=m;t.className='toast show '+(type||'');setTimeout(()=>t.classList.remove('show'),3000)}

document.addEventListener('DOMContentLoaded',function(){inicializarMapa();if(typeof R!=='undefined'&&R.length>0){recintos=R.filter(r=>r.la&&r.lo);llenarFiltros();renderMapa()}cargarTodosDatos();document.getElementById('modalClose').addEventListener('click',cerrarModal);document.getElementById('modalOverlay').addEventListener('click',e=>{if(e.target.id==='modalOverlay')cerrarModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')cerrarModal()});document.getElementById('selDep').addEventListener('change',()=>{actualizarMunicipios();document.getElementById('selMuni').value='Todos';renderMapa()});document.getElementById('selMuni').addEventListener('change',renderMapa);document.getElementById('selEstado').addEventListener('change',renderMapa);document.getElementById('searchInput').addEventListener('input',function(){buscar(this.value,'searchResults')});document.getElementById('floatSearchInput').addEventListener('input',function(){buscar(this.value,'floatResults')});document.getElementById('btnSearch').addEventListener('click',()=>{const f=document.getElementById('floatSearch');f.classList.toggle('show');if(f.classList.contains('show'))document.getElementById('floatSearchInput').focus()});document.getElementById('floatClose').addEventListener('click',()=>{document.getElementById('floatSearch').classList.remove('show')});document.addEventListener('click',e=>{if(!e.target.closest('.search-box')&&!e.target.closest('.search-results')&&!e.target.closest('.float-search')){document.getElementById('searchResults').classList.remove('show');document.getElementById('floatResults').classList.remove('show')}});document.getElementById('btnPanel').addEventListener('click',()=>{document.getElementById('panel').classList.toggle('show')});document.addEventListener('click',e=>{if(window.innerWidth<=768&&!e.target.closest('.panel')&&!e.target.closest('#btnPanel'))document.getElementById('panel').classList.remove('show')});document.getElementById('btnRefresh').addEventListener('click',async()=>{const b=document.getElementById('btnRefresh');b.classList.add('spinning');await cargarTodosDatos();b.classList.remove('spinning')})});
